alias e='emacs'
alias ll='ls -al'
alias ls='ls -aF --color'

export JAVA_HOME=/usr/local/lib/jdk
export SCALA_HOME=/usr/local/lib/scala
export PATH=$PATH:/usr/local/lib/jdk/bin:/usr/local/lib/scala/bin

. /.gvm/bin/gvm-init.sh
