FROM centos
MAINTAINER Kang Chang Ki

# install basic packages
RUN yum -y install wget tar openssh-server

RUN mkdir /var/run/sshd
RUN echo 'root:screencast' |chpasswd

EXPOSE 22
CMD    ["/usr/sbin/sshd", "-D"]

# versions
ENV NODE_VER 0.10.30

### installed directory
RUN mkdir /installed
WORKDIR /installed

# install node
RUN wget http://nodejs.org/dist/v$NODE_VER/node-v$NODE_VER-linux-x64.tar.gz
RUN tar xfvz node-v$NODE_VER-linux-x64.tar.gz
RUN ln -s node-v$NODE_VER-linux-x64 node

### work directory
ADD ./work /work
WORKDIR /work

# setup .bashrc
RUN cat .bashrc >> ~/.bashrc

# main
# CMD /installed/node/bin/node /work/index.js
